
import "./globals.css";
import Theme from "./Theme";
import { AppProvider } from "./hooks/AppContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "BookStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppProvider>
          <Toaster position="top-right" toastOptions={{
            duration: 4000, style: {
              background: "var(--background)",
              color: "var(--foreground)",
              borderRadius: "10px",
              border: "1px solid var(--foreground)",
              boxShadow: "0px 1px 1px var(--foreground)"
            }
          }} />
          <Theme />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
