import { Geist, Geist_Mono, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./hooks/AppContext";
import Theme from "./Theme";
import Snowfall from "react-snowfall";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "BookStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppProvider>
          <Toaster position="top-right" toastOptions={{
            duration: 4000, style: {
              background: "var(--background)",
              color: "var(--foreground)",
              borderRadius: "10px",
              border: "1px solid var(--foreground)",
              boxShadow: "0px 1px 1px var(--foreground)"
            }
          }} />
          {children}
          <Theme />
        </AppProvider>
      </body>
    </html>
  );
}
