import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AppProvider } from "@/store/AppContext";
import { ThemeProvider } from "next-themes";
import Theme from "@/components/Theme";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <AppProvider>
            {children}
            <Toaster position="top-center" toastOptions={{
              duration: 4000, style: {
                background: "var(--background)",
                color: "var(--foreground)",
                borderRadius: "10px",
                border: "1px solid var(--foreground)",
                boxShadow: "0px 1px 1px var(--foreground)"
              }
            }} />
            <Theme />
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
